### ISSUE TITLE
Unsafe comparison with nil at Paginator.Ecto.Query

### ISSUE THREAD

**Issue by Ovsov** [duffelhq/paginator#29]
Hello there! 

There is аn error about unsafe comparison with nil which occurs while using multiple `cursor_fields`.
I checked up pull requests and found [solution](https://github.com/duffelhq/paginator/pull/24) by @0nkery.  It opened more than month ago however there are still no reactions.  Are you going to review it? 

Thanks)

**Comment by sergey-chechaev** [comment]
👍

**Comment by AndrewDryga** [comment]
Hey @stevedomin, If you don't feel like maintaining this library, I would be happy to take it from here. 

(I would move it to our org, merge with `ecto_paging` which is somewhat loosing versus this library and leave a large note about origins of source code so that people know that you were the original author and then work on maintaining it).

**Comment by stevedomin** [comment]
v0.4.1 is out! Sorry for the wait guys
