### ISSUE TITLE
Change description to match actual behaviour

### ISSUE THREAD

**Issue by hauleth** [duffelhq/paginator#8]
What this library provide is **index-based pagination** which is different from [cursor-based one](https://www.postgresql.org/docs/current/static/plpgsql-cursors.html). This difference may not be the relevant for most web developers, but for DBA it is quite important. The main difference is that cursor-based pagination can be bidirectional, but it comes at the price: you need to maintain continuous connection to DB which mean that this is not stateless pagination.

**Comment by stevedomin** [comment]
Hi @hauleth.

Thanks for the feedback.

I agree that cursor-based pagination can be misleading for some people but I chose it because the industry seemed to settle on that word for describing that kind of pagination.

Examples:

- https://stripe.com/docs/api#pagination
- https://developer.gocardless.com/api-reference/#api-usage-cursor-pagination
- https://api.slack.com/docs/pagination#cursors
- http://graphql.org/learn/pagination/
- https://developer.twitter.com/en/docs/basics/cursoring

I mentioned in the README that this method is also called "keyset pagination".
